version: "3.8"

services:
  weather-app:
    build: .
    container_name: weather-app-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_APPLICATION_JSON={"weather.api.key":"${API_KEY}"}
